### ISSUE TITLE
Movement Speed is Uncapped

### ISSUE THREAD

**Issue by Lain-tf** [shalrathy/quakespasm-shalrathy#1]
If this is intended, it should probably be listed prominently on the intro page.

**Comment by shalrathy** [comment]
There are no changes to code near the physics or movement behavior. If there are changes to movement speed it is unintended and confusing to me.
The base code is the quakespasm version mentioned in the release notes compiled to SDL2. I cannot find any recent changes to movement speed in the quakespasm release log https://sourceforge.net/p/quakespasm/news/ . I do not know why movement speed would be different in this port compared to normal quakespasm.
